model:
  name: gpt2

data:
  base_path : "C:/Users/User/PycharmProjects/CUK_NL_team3"
  train_path: base_path + "./data/split_data/train_explicit.jsonl"
  val_path:   base_path + "./data/split_data/val_explicit.jsonl"
  test_path:  base_path + "./data/split_data/test_explicit.jsonl"
  condition: explicit

train:
  output_dir: logs/explicit_gpt2
  epochs: 9
  batch_size: 8
  grad_accum: 2
  lr: 1.0e-4
  warmup_steps: 1000
  max_length: 512
  logging_steps: 50
  weight_decay: 0.01
